config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root "pages#landing"

  resources :goals, :only => [:index, :new, :create, :update, :edit, :destroy]

  resources :reports, :only => [:index, :new, :create, :show, :update]

  resources :users, :only => [:show, :edit, :update, :index]

  resources :friendships, :only => [:create, :index, :show]

  get '/notifications' => 'notifications#index'
  
  get '/users/:id/add_kid' => 'users#add_kid'

  get '/friendships/:friendship_id/accept_friend' => 'friendships#accept_friend'

  get 'pages/landing'

  get '/notifications/:goal_id/received_prize' => 'goals#received_prize'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :receiver, class_name: "User"
	belongs_to :requester, class_name: "User"

	
	def self.find_pending
		Friendship.where(status: "Pending")
	end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :parent, :class_name => 'User'
	belongs_to :kid, :class_name => 'User'

	has_many :reports, :dependent => :destroy

	def self.find_completed
		Goal.where(prize_status: 0)
	end

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :goal
	after_update :goal_update #this will need to change when parent has to approve it

	belongs_to :kid, class_name: "User"

	def goal_update
		self.goal.progress += self.amount 
		self.goal.save
		if self.goal.progress >= self.goal.target
			self.goal.status = 1
			self.goal.prize_status = 0	
			self.goal.save
			#UserMailer.goal_completed_email(User.find(Goal.find(self.goal).parent_id)).deliver
		end
	end

	def self.find_pending
		Report.where(status: "0")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :goals, foreign_key: "kid_id"
  
  has_many :kids, class_name: "User", foreign_key: "parent_id"
  belongs_to :parent, class_name: "User"

  has_many :friendships, foreign_key: "requester_id"
  has_many :receivers, :through => :friendships

  #after_create :send_welcome_email

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	def self.filter(query)
		query.blank? ? User.all : User.where("name || email LIKE '%#{query}%'")
	end

  protected

  def send_welcome_email
    #UserMailer.welcome_email(self).deliver
  end


  def friendships

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :notification_counter

  
  protect_from_forgery with: :exception

  def stored_location_for(resource)
    nil
  end

  def after_sign_in_path_for(resource)
    goals_path
  end

  def auth_user!
    redirect_to root_path unless user_signed_in?
  end

  def authenticate_kid!
  	unless (user_signed_in? && current_user.role == "kid")
  		flash[:alert] = "Only kids can do that!"
  		redirect_to root_path
  	end
  end

  def authenticate_parent!
  	unless (user_signed_in? && current_user.role == "parent")
  		flash[:alert] = "Only parents can do that!"
  		redirect_to root_path
  	end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :role
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :age
    devise_parameter_sanitizer.for(:sign_up) << :gender
    #devise_parameter_sanitizer.for(:account_update) << :handle
  end

  def notification_counter
    @length = 0
    @report_notifications = Report.find_pending
    @friend_request_notifications = Friendship.find_pending
    @prizes_notifications = Goal.find_completed
    if user_signed_in?
      @report_notifications.each do |notif|
        if notif.goal_id
          if User.find(Goal.find(notif.goal_id).kid_id).parent_id == current_user.id
            @length += 1
          end
        end
      end
      @friend_request_notifications.each do |notif|
        if (notif.receiver_id || notif.requester_id)
          if (User.find(notif.receiver_id).id == current_user.id)
            @length += 1
          end
        end
      end
      @prizes_notifications.each do |notif|
        if notif.kid_id
          if (User.find(notif.kid_id).id == current_user.id) || (User.find(notif.kid_id).parent_id == current_user.id)
            @length += 1
          end
        end
      end
    end
    @length
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :auth_user!

	def index
		@friendships = Friendship.all
	end

	def create
		@friendship = Friendship.new
		@friendship.requester_id = current_user.id
		@friendship.receiver_id = User.find(params[:receiver_id]).id
		@friendship.status = "Pending"
 		@friendship.save
		redirect_to :action => :index
	end

	def show
		@friendship = Friendship.find(params[:id])
	end

	def accept_friend
		@friendship = Friendship.find(params[:friendship_id])
		@friendship.status = "Accepted"
		@friendship.save
		redirect_to friendships_path
	end

end 

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	before_action :auth_user!
	#before_create :authenticate_parent!

	def index
		@goals = Goal.all
		@report = Report.new
	end

	def new
		@goal = Goal.new
		@kid_names = current_user.kids.pluck(:name, :id)
	end

	def edit
		@goal = Goal.find(params[:id])
		@kid_names = current_user.kids.pluck(:name, :id)
	end

	def create
		@goal = Goal.new(goal_params)
		@goal.progress = 0
		@goal.status = 0
		@goal.prize_status = -1
		@goal.save
		redirect_to :action => :index
	end

	def update
		@goal = Goal.find(params[:id])
		@goal.update!(goal_params)
		@goal.save
		redirect_to goals_path
	end

	def destroy
		@goal = Goal.find(params[:id])
		@goals = Goal.all
		@goals.delete(@goal.id)
		redirect_to goals_path
	end

	def received_prize
		@goal = Goal.find(params[:goal_id])
		@goal.update_attributes(prize_status: 1)
		@goals = Goal.all
		@goal.destroy
		@goals.delete(@goal.id)
		redirect_to '/notifications'
	end

	private

	def goal_params
		params.require(:goal).permit(:title, :description, :target, :unit, :prize, :status, :kid_id)
	end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController 
	before_action :auth_user!


def index
    @report_notifications = Report.find_pending
    @friend_request_notifications = Friendship.find_pending
    @prizes_notifications = Goal.find_completed
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def landing
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :auth_user!
	#before_action :authenticate_kid!

	def index
		@reports = Report.all
	end

	def new
		@report = Report.new
	end

	def create
		@report = Report.new(report_params)
		@report.status = 0
		@report.save
		flash[:notice] = "Progress successfully submitted!"
		redirect_to goals_path
	end

	def show
		@report = Report.find(params[:id])
	end

	def update
		@report = Report.find(params[:id])
		@report.status = 1
		@report.save
		redirect_to "/notifications"
	end

	private

	def report_params
		params.require(:report).permit(:amount, :kid_id, :goal_id, :status)
	end

end

app/controllers/users_controller.rb
    class UsersController < ApplicationController
        before_action :authenticate_user!

	def index
		@users = User.filter(params[:q]).paginate(:per_page => 3, :page => params[:page])
        #@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
    	@user = User.find(params[:id])
    end

    def update
    	@user = User.find(params[:id])
        @user.update!(user_params)
        #@user.pick_avatar
        @user.save
        redirect_to user_path
    end

    def add_kid
        @user = User.find(params[:id])
        @user.update_attributes(parent_id: current_user.id)
        redirect_to "/users"
    end

    def pick_avatar
      @user = User.find(params[:id])
      @user.update_attributes(avatar: "http://www.clipartbest.com/cliparts/di8/XKg/di8XKgXie.png")
      @user.save
    end

    private

        def user_params
            params.require(:user).permit(:email, :name, :age, :gender, :parent_id, :bio, :username, :role, :avatar)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper

def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/friendships/index.html.erb
<h3>My Friends</h3>
<% @friendships.each do |friendship| %>
	<% if friendship.requester_id == current_user.id && friendship.status == "Accepted" %>
		<b><%= link_to "#{User.find(friendship.receiver_id).name}", "/users/#{friendship.receiver_id}/" %><b/><br>
	<% elsif friendship.receiver_id == current_user.id && friendship.status == "Accepted" %>
		<b><%= link_to "#{User.find(friendship.requester_id).name}", "/users/#{friendship.requester_id}/" %></b><br>
	<% end %>
<% end %>

<br>

<p><b>Pending Friend Requests</p></b>
<% @friendships.each do |friendship| %>
	<% if friendship.requester_id == current_user.id || friendship.receiver_id == current_user.id %>  
		<% if friendship.status == "Pending" %>
		  <em><%= "Your friendship with #{User.find(friendship.receiver_id).name} is #{friendship.status}!" %></em>
			<% if friendship.receiver_id == current_user.id && friendship.status == "Pending" %>
				<%= link_to "Accept Friend Request", "/friendships/#{friendship.id}/accept_friend", class: "btn btn-sm btn-primary btn-embossed approve" %>
				<br>
			<% end %>
			<br>
		<% end %>
	<% end %>
<% end %>

app/views/goals/edit.html.erb
<h3>Edit Goal</h3>	

<%= form_for(@goal, :url => goal_path(@goal), :method => :put) do |f| %>
	
	<%= f.select :kid_id, @kid_names %> 


<script>

$("select").selectpicker({style: 'btn btn-primary', menuStyle: 'dropdown-inverse'});

</script>

	<%= f.text_field :title, class: "form-control", placeholder: "Title" %>


	
	<%= f.text_field :description, class: "form-control", placeholder: "Description" %>



	
	<%= f.number_field :target, class: "form-control", placeholder: "Target amount" %>


	<%= f.select :unit, options_for_select(["minutes", "hours", "days", "times"], :id => "unit-select") %>
<script>

$("select").selectpicker({style: 'btn btn-primary', menuStyle: 'dropdown-inverse'});

</script>

	

	
	<%= f.text_field :prize, class: "form-control", placeholder: "Prize" %>


	<%= f.submit class: "btn btn-primary btn-embossed" %>

	<br><br>

	<%= link_to "Delete Goal", "/goals/#{@goal.id}", method: "delete", class: "btn btn-danger btn-sm" %>

<% end %>

app/views/goals/index.html.erb
<div class="trophy">
		<%= image_tag('flat-ribbon-badget2.png')%>
	</div>

<div class="goalstitle">
	<h2>Goals</h2>
	
</div>

<% if current_user.role == "parent" %>
<%= link_to "Create a New Goal", "goals/new" , :class => "btn btn-primary btn-embossed"%><br>
<% end %>
<br>

<% if current_user.goals.length == 0 && current_user.role == "kid"%>
	<%= "You have no open goals! Check back later for more." %><br>
<% end %>
<% collapse_count = 1 %>
<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>
<% @goals.each do |goal| %>
	<% total_submitted = 0 %>
	<% goal.reports.each do |report| %>
		<% total_submitted += report.amount unless report.amount == 0 %>
	<% end %>

	<% if total_submitted >= goal.target && goal.status == 0 && current_user.role == "kid" %>


		<div class = "prizenotice">
			<%= image_tag 'trophy-dribbble.gif' %>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<%= "Congrats! You have completed"%><em><%=" #{goal.title}!"%></em><%= "Just wait for your parent's approval!" %><br>



		</div>
		<br>
	<% end %>

	<% if current_user.role == "kid" && goal.kid_id == current_user.id %>
	<div class="panel-group" id="accordion">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href=<%= "#collapse#{collapse_count}" %>>
					<span style="font-size: 25px; font-weight: bold;"><%= "#{goal.title}"%></span>
					<!-- Submit new report modal goes here -->
					
					<button class="btn btn-primary btn-embossed btn-xs" data-toggle="modal" data-target=<%= "#reportmodal#{goal.id}" %> id="btn-add"><span class="fui-plus"></span></button>
				</a>
				</h4>
			</div>
			<div id= <%= "collapse#{collapse_count}" %> class="panel-collapse collapse">
				<div class="panel-body">
					<% if goal.status == 0 %>
						<% goal_percent = ((goal.progress.to_f/goal.target.to_f).to_f * 100).round(2) %>
							<%= "Goal is #{goal_percent}% complete!"%> <em><%= "#{goal.progress} out of #{goal.target} #{goal.unit} done." %></em><br><br>
							<div class="progress">
								<div class="progress-bar" style="width: <%= goal_percent %>%;"></div>
							</div>
							<%= "Description: #{goal.description}" %><br>
							<b><%= "Prize is #{goal.prize}!" %></b><br>
							<span class="miniwords"><%= link_to "#{User.find(goal.kid_id).name}'s profile", "/users/#{goal.kid_id}" %></span><br>
							<!-- Submit new report modal here also -->
						
						<button class="btn btn-primary btn-embossed" data-toggle="modal" data-target=<%="#reportmodal#{goal.id}"%>>Make Report</button>
						
						
					<% else %>
							<%= "Goal is complete! Your parent approved your progress!" %><br>
							<%= link_to "Prize Received", "/notifications/#{goal.id}/received_prize", class: "btn btn-primary btn-embossed" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<% elsif current_user.role == "parent" %>
	<% current_user.kids.pluck(:id).each do |id| %>
	<% if goal.kid_id == id %>
	<div class="panel-group" id="accordion">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
				<a data-toggle="collapse" data-parent="#accordion" href= <%= "#collapse#{collapse_count}" %> >
					<span style="font-size: 25px; font-weight: bold;"><%= "#{goal.title}  " %></span><em><%= "- #{User.find(goal.kid_id).name}"%></em>
				</a>
				</h4>
			</div>
			<div id= <%= "collapse#{collapse_count}" %> class="panel-collapse collapse">
				<div class="panel-body">
					<% if goal.status == 0 %>
					<% goal_percent = ((goal.progress.to_f/goal.target.to_f).to_f * 100).round(2) %>
					<%= "Goal is #{goal_percent}% complete!"%> <em><%= "#{goal.progress} out of #{goal.target} #{goal.unit} done." %></em><br><br>
					<div class="progress">
						<div class="progress-bar" style="width: <%= goal_percent %>%;"></div>
					</div>
					<%= "Description: #{goal.description}" %><br>
					<b><%= "Prize is #{goal.prize}!" %></b><br>
					<span class="miniwords"><%= link_to "#{User.find(goal.kid_id).name}'s profile", "/users/#{goal.kid_id}" %></span><br>
					<%= link_to "Edit Goal", edit_goal_path(goal.id), class: "btn btn-primary btn-embossed btn-xs" %>
					<% else %>
					<%= "Goal is complete!" %><br>
					<%= "Prize is #{goal.prize}." %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<% end %>
	<% end %>
	<% collapse_count += 1 %>
	<div class="modal fade" id=<%="reportmodal#{goal.id}"%> tabindex="-1" role="dialog" aria-labelledby="reportmodalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title" id="reportmodalLabel">Add Progress to <%= "#{goal.title}" %></h4>
				</div>
				<div class="modal-body">
					<%= form_for(@report, :url => '/reports') do |f| %>
					<div id="report-fields">
						<div id="amount-field"><%= f.text_field :amount, class: "form-control", placeholder: "Amount" %></div>
						<div id="unit-field"><%= "  " + goal.unit %></div>
					</div>
					<%= f.hidden_field :goal_id, :value => goal.id %>
					<%= f.submit "Report my Progress", class: "btn btn-primary btn-embossed" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/goals/new.html.erb
<h3>New Goal</h3>

<% if @goal.errors.any? %>
	<div class="errors">
		<ul>	
			<%@goal.errors.full_messages.each do |message| %>
				<li><%=message%></li>
			<%end%>
		</ul>
	</div>
<%end%>

<%= form_for(@goal, :url => '/goals') do |f| %>
	
	<%= f.select :kid_id, @kid_names %> 


<script>

$("select").selectpicker({style: 'btn btn-primary', menuStyle: 'dropdown-inverse'});

</script>

	<%= f.text_field :title, class: "form-control", placeholder: "Title" %>


	
	<%= f.text_field :description, class: "form-control", placeholder: "Description" %>



	
	<%= f.number_field :target, class: "form-control", placeholder: "Target amount" %>


	<%= f.select :unit, options_for_select(["minutes", "hours", "days", "times"], :id => "unit-select") %>
<script>

$("select").selectpicker({style: 'btn btn-primary', menuStyle: 'dropdown-inverse'});

</script>

	

	
	<%= f.text_field :prize, class: "form-control", placeholder: "Prize" %>


	<%= f.submit class: "btn btn-primary btn-embossed" %>
<% end %>

app/views/layouts/_loginpartial.html.erb
<!-- MODAL CODE HERE -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Log in</h4>
                  </div>
                  <div class="modal-body">
                    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

                      <div><%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email"%></div>
                      <div><%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password"%></div>
                      
                      <label class="checkbox" for="checkbox1">
                        <input type="checkbox" value="remember_me" id="checkbox1" data-toggle="checkbox">
                        Remember me
                      </label>

                      <div><%= f.submit "Log in", class: "btn btn-primary btn-lg btn-embossed" %></div>

                    <% end -%><br>
                    <%= render "devise/shared/links" %>
                  </div>
                </div>
              </div>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kazoo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <%= csrf_meta_tags %>
  </head>
  <body class="<%=controller_name%>">
    <div class="wrapper">
      <nav class="navbar navbar-inverse navbar-embossed navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
          <span class="sr-only">Toggle navigation</span>
          </button>
          <%= link_to 'kazoo', root_path, class: "navbar-brand"%>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-01">
          <ul class="nav navbar-nav">
            <li><%= link_to 'goals', goals_path %></li>
            <li><%= link_to 'friends', "/friendships" %></li>
            <li><a href='/notifications'>notifications<span class="navbar-new"><%= @length %></span></a></li>
          </ul>
          <div class = "navbar-right">
            <% if user_signed_in? %>
            <button class="btn btn-default navbar-btn btn-xs" type="button">
            <%=link_to 'sign out', destroy_user_session_path, :method => :delete, class: "navbar-link"%>
            </button>
            <% else %>
            
            <!--BUTTON TO LAUNCH MODAL -->
            <button class="btn btn-default navbar-btn btn-sm" data-toggle="modal" data-target="#myModal">
            Log in           
            </button>
            
            <% end %>
          </div>
          <% if current_user %>
          <p class="navbar-text navbar-right">Signed in as
          <%= link_to current_user.name, "/users/#{current_user.id}", class: "navbar-link" %>
          </p>
          <% end %>
          
          <div class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <div class="input-group"  >
                <%= form_tag users_path, :method => 'GET' do  %>
                    <%= text_field_tag 'q', params[:q], class: "form-control", id: "navbarInput-01", type: "search", placeholder: "search" %>
                    <span class="input-group-btn">
                    <button type="submit" class="btn"><span class='fui-search'></span></button>
                    </span>
                <% end %>
              </div>
            </div>
          </div>
          
          
          </div><!-- /.navbar-collapse -->
          </nav><!-- /navbar -->
          
          <br><br>
          
          <div class="container">
            <!-- <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p> -->
            
            <%= yield %>

          </div>
          <div class="push"></div>

        </div>

       
        <div class="footer navbar-inverse">
        <% unless params[:controller] == "pages" %>
          <div id="cornerdino">
            <%= image_tag 'dino3.png' %>
          </div> 
        <% end %>         


          <div class="footer-text">
            <p class="navbar-text"> &copy Sarah Schachman & Allie Ivener 2014 </p>
          </div>
        </div>
       
        
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Log in</h4>
              </div>
              <div class="modal-body">
                <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

                  <div><%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Email"%></div>
                  <div><%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password"%></div>
                  
                  <label class="checkbox" for="checkbox1">
                    <input type="checkbox" value="remember_me" id="checkbox1" data-toggle="checkbox">
                    Remember me
                  </label>

                  <div><%= f.submit "Log in", class: "btn btn-primary btn-lg btn-embossed" %></div>

                <% end -%><br>
                <%= render "devise/shared/links" %>
              </div>
            </div>
          </div>
        </div>
       

      </body>
    </html>

app/views/notifications/index.html.erb
<h3>Notifications</h3>


<% if current_user.role == "parent" %>
	<p><b><em>Report Notifications</em></p></b>

	<% @report_notifications.each do |notification| %>
		<% if notification.goal_id %>
			<% if User.find(Goal.find(notification.goal_id).kid_id).parent_id == current_user.id %>
				<%= link_to "Approve", report_path(notification.id), method: "put", class: "btn btn-primary btn-embossed btn-xs approve" %> &nbsp;&nbsp;<%= notification.amount %> <%= Goal.find(notification.goal_id).unit %> toward <%= Goal.find(notification.goal_id).title %> <br><br>
			<% end %>
		<% end %>
	<% end %>
<% end %>

<p><b><em>Friend Requests</em></p></b>

<% @friend_request_notifications.each do |notification| %>
	<% if notification.receiver_id %>
		<% if notification.receiver_id == current_user.id  %>
			<%= link_to "Accept", "/friendships/#{notification.id}/accept_friend", class: "btn btn-primary btn-embossed btn-xs approve"  %>&nbsp;&nbsp;<%= "#{User.find(notification.requester_id).name} has sent you a friend request!" %><br><br>
			
		<% end %>
	<% end %>
<% end %>


<p><b><em>Prizes Won</em></p></b>

<% @prizes_notifications.each do |notification| %>
	<% if notification.kid_id %>
		<% if current_user.role == "parent" && notification.prize_status == 0%>
			<% if User.find(notification.kid_id).parent_id == current_user.id %>
				<%= "#{User.find(notification.kid_id).name} has completed "%><em><%= "#{notification.title}."%></em><%=" The prize is " %> <b><%="#{Goal.find(notification.id).prize}!" %></b><br>
			<% end %>
		<% elsif current_user.role == "kid" %>
			<% if User.find(notification.kid_id).id == current_user.id %>
				<%= link_to "Prize Received", "/notifications/#{notification.id}/received_prize", class: "btn btn-primary btn-embossed btn-xs approve" %>&nbsp;&nbsp;<%= "You completed"%><em><%=" #{notification.title}!" %></em>
				<br><br>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/pages/landing.html.erb
<div class="slide1">
	<%= image_tag("full_logo3.png", :class => "text-center") %><br>	
        <% if !current_user %>
            <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-primary btn-hg btn-embossed", id: "signup" %><br><br>
        <% else %>
            <br><br>
        <% end %>

    <p id="mission">A family-friendly, goal-based social platform that motivates kids to get out from behind the screen.</p>
    <br><br>

    <p>scroll down</p>
</div>

<div class="slide2">
    <%= image_tag('baby.jpg') %>
</div>

<div class="slide3">
    <%= image_tag('playingoutside.jpg') %>
</div>

<div class="slide4">
    <%= image_tag('motivate.jpg') %>
</div>

<div class="slide5">
    <%= image_tag('withipad.jpg') %>
</div>

<div class="slide6">
    <%= image_tag('boyhomework.jpg') %>
    <div class="signupbutton">
    <%= link_to "Sign up now", new_registration_path(resource_name), class: "btn btn-primary btn-hg btn-embossed", id: "signup2" %>
    </div>
</div>

app/views/reports/index.html.erb
<h1>Report Index Page</h1>

<ul>
	<% @reports.each do |report| %>
		<% if report.status == 0 && current_user.role == "parent" %>
			<%= "REPORT: #{report.amount}" %>
			<%= link_to "Approve", report_path(report.id), method: "put" %>
		<% end %>
	<% end %>
</ul>